# Generated by Django 5.1.4 on 2024-12-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLab_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='book_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
