# Generated by Django 5.1.4 on 2024-12-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLab_App', '0002_bookslibrary_book_language_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
