# Generated by Django 5.1.4 on 2024-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLab_App', '0003_alter_categories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
