# Generated by Django 5.1.4 on 2024-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLab_App', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
