# Generated by Django 5.1.4 on 2024-12-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLab_App', '0006_bookslibrary_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
