# Generated by Django 5.1.4 on 2024-12-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookLab_App', '0007_bookslibrary_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslibrary',
            name='is_free',
        ),
    ]
